In [1]:
import pandas as pd

In [7]:
people = {
    "first": ["Retaj", "Ahmed", "Marwa"],   
    "second": ["Ahmed", "Adel", "Salah"],  
    "email": ["retagahmed@gmail.com", "ahmedadel@gmail.com", "marwasalah@gmail.com"]
}

In [8]:
people['email']

['retagahmed@gmail.com', 'ahmedadel@gmail.com', 'marwasalah@gmail.com']

In [10]:
df = pd.DataFrame(people)
df

   first second                 email
0  Retaj  Ahmed  retagahmed@gmail.com
1  Ahmed   Adel   ahmedadel@gmail.com
2  Marwa  Salah  marwasalah@gmail.com

In [14]:
df['email']

0    retagahmed@gmail.com
1     ahmedadel@gmail.com
2    marwasalah@gmail.com
Name: email, dtype: object

In [16]:
df.email

0    retagahmed@gmail.com
1     ahmedadel@gmail.com
2    marwasalah@gmail.com
Name: email, dtype: object

is the same thing

In [13]:
type(df['email'])

pandas.core.series.Series

#Series is single column

In [18]:
df[['second','email']]

  second                 email
0  Ahmed  retagahmed@gmail.com
1   Adel   ahmedadel@gmail.com
2  Salah  marwasalah@gmail.com

In [20]:
#to get columns
df.columns

Index(['first', 'second', 'email'], dtype='object')

# هيعرض لك بيانات الشخص صاحب الإيميل ده
df.loc['retagahmed@gmail.com']

In [24]:
#to get rows
df.iloc[1]

first                   Ahmed
second                   Adel
email     ahmedadel@gmail.com
Name: 1, dtype: object

In [25]:
#to get multiple rows
df.iloc[[1,2]]

   first second                 email
1  Ahmed   Adel   ahmedadel@gmail.com
2  Marwa  Salah  marwasalah@gmail.com

In [38]:
#to get multiple rows with select specific location columns
df.iloc[[1,2],2]

1     ahmedadel@gmail.com
2    marwasalah@gmail.com
Name: email, dtype: object

iloc searching by integer location
loc searching by lable

In [44]:
df.loc[[1,2],['email','second']]

                  email second
1   ahmedadel@gmail.com   Adel
2  marwasalah@gmail.com  Salah

In [51]:
df.loc[0:2,'first']

0    Retaj
1    Ahmed
2    Marwa
Name: first, dtype: object

In [52]:
df.loc[0:2,'first':]

   first second                 email
0  Retaj  Ahmed  retagahmed@gmail.com
1  Ahmed   Adel   ahmedadel@gmail.com
2  Marwa  Salah  marwasalah@gmail.com