In [1]:
import pandas as pd

In [2]:
people = {
    "first": ["Retaj", "Remass", "Marwa"],   
    "second": ["Ahmed", "Ahmed", "Salah"],  
    "email": ["retagahmed@gmail.com", "ahmedadel@gmail.com", "marwasalah@gmail.com"]
}

In [3]:
df = pd.DataFrame(people)
df

    first second                 email
0   Retaj  Ahmed  retagahmed@gmail.com
1  Remass  Ahmed   ahmedadel@gmail.com
2   Marwa  Salah  marwasalah@gmail.com

In [4]:
#comparison
filt = df['second'] == 'Ahmed'
filt

0     True
1     True
2    False
Name: second, dtype: bool

In [5]:
df[filt]

    first second                 email
0   Retaj  Ahmed  retagahmed@gmail.com
1  Remass  Ahmed   ahmedadel@gmail.com

In [6]:
#OR
df[df['second'] == 'Ahmed']

    first second                 email
0   Retaj  Ahmed  retagahmed@gmail.com
1  Remass  Ahmed   ahmedadel@gmail.com

In [7]:
#OR
df.loc[filt]

    first second                 email
0   Retaj  Ahmed  retagahmed@gmail.com
1  Remass  Ahmed   ahmedadel@gmail.com

In [8]:
df.loc[filt,'email']

0    retagahmed@gmail.com
1     ahmedadel@gmail.com
Name: email, dtype: object

In [9]:
filt = (df['second']== 'Ahmed') & (df['first'] == 'Retaj')
filt

0     True
1    False
2    False
dtype: bool

In [10]:
df.loc[filt,'email']

0    retagahmed@gmail.com
Name: email, dtype: object

In [11]:
filt = (df['second']== 'Ahmed') | (df['first'] == 'Retaj')
filt

0     True
1     True
2    False
dtype: bool

In [14]:
df.loc[filt,'email']

0    retagahmed@gmail.com
1     ahmedadel@gmail.com
Name: email, dtype: object

In [15]:
#Negate that filter (opposite results)
df.loc[~filt,'email']

2    marwasalah@gmail.com
Name: email, dtype: object