In [1]:
import pandas as pd

In [2]:
people = {
    "first": ["Retaj", "Ahmed", "Marwa"],   
    "second": ["Ahmed", "Adel", "Salah"],  
    "email": ["retagahmed@gmail.com", "ahmedadel@gmail.com", "marwasalah@gmail.com"]
}

In [3]:
people

{'first': ['Retaj', 'Ahmed', 'Marwa'],
 'second': ['Ahmed', 'Adel', 'Salah'],
 'email': ['retagahmed@gmail.com',
  'ahmedadel@gmail.com',
  'marwasalah@gmail.com']}

In [4]:
df = pd.DataFrame(people)
df

   first second                 email
0  Retaj  Ahmed  retagahmed@gmail.com
1  Ahmed   Adel   ahmedadel@gmail.com
2  Marwa  Salah  marwasalah@gmail.com

In [5]:
df.set_index('email')

                      first second
email
retagahmed@gmail.com  Retaj  Ahmed
ahmedadel@gmail.com   Ahmed   Adel
marwasalah@gmail.com  Marwa  Salah

In [6]:
df

   first second                 email
0  Retaj  Ahmed  retagahmed@gmail.com
1  Ahmed   Adel   ahmedadel@gmail.com
2  Marwa  Salah  marwasalah@gmail.com

In [7]:
#Index (Sorting)
df.set_index('email',inplace=True)

In [8]:
df

                      first second
email
retagahmed@gmail.com  Retaj  Ahmed
ahmedadel@gmail.com   Ahmed   Adel
marwasalah@gmail.com  Marwa  Salah

In [9]:
df.index

Index(['retagahmed@gmail.com', 'ahmedadel@gmail.com', 'marwasalah@gmail.com'], dtype='object', name='email')

In [10]:
df.loc['retagahmed@gmail.com']

first     Retaj
second    Ahmed
Name: retagahmed@gmail.com, dtype: object

In [12]:
df.loc['retagahmed@gmail.com','second']

'Ahmed'

In [16]:
df.iloc[1]

first     Ahmed
second     Adel
Name: ahmedadel@gmail.com, dtype: object

In [17]:
df.reset_index(inplace=True)
df

                  email  first second
0  retagahmed@gmail.com  Retaj  Ahmed
1   ahmedadel@gmail.com  Ahmed   Adel
2  marwasalah@gmail.com  Marwa  Salah

In [20]:
df.loc[0]

email     retagahmed@gmail.com
first                    Retaj
second                   Ahmed
Name: 0, dtype: object